import { ResumeData } from "./types";

export const initialResumeData: ResumeData = {
  id: "sample-tech-lead",
  title: "Senior Full-Stack Engineer Resume",
  personalInfo: {
    fullName: "Alex Rivera",
    jobTitle: "Senior Full-Stack & Cloud Architect",
    email: "alex.rivera@example.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    website: "https://alexrivera.dev",
    linkedin: "linkedin.com/in/alex-rivera-tech",
    github: "github.com/alexrivera",
    avatarUrl: "",
  },
  summary:
    "High-impact Senior Full-Stack Engineer with 8+ years architecting resilient distributed systems, real-time analytics platforms, and polished web applications. Proven track record scaling microservices from zero to 15M+ active users while driving 35% latency reductions. Passionate about developer tooling, clean code ergonomics, and mentorship.",
  experience: [
    {
      id: "exp-1",
      role: "Staff Software Engineer",
      company: "AetherScale Technologies",
      location: "San Francisco, CA",
      startDate: "2022-03",
      endDate: "Present",
      current: true,
      bullets: [
        "Architected and delivered event-driven ingestion pipeline handling 1.2B daily events with 99.995% uptime using Go, Kafka, and Next.js.",
        "Led team of 12 engineers across US and Europe, establishing trunk-based development and reducing deployment cycle times by 48%.",
        "Pioneered migration from legacy monolith to modular micro-frontends, accelerating cross-functional feature velocity by 3x.",
      ],
    },
    {
      id: "exp-2",
      role: "Senior Full-Stack Engineer",
      company: "Nexus Financial Cloud",
      location: "New York, NY",
      startDate: "2019-06",
      endDate: "2022-02",
      current: false,
      bullets: [
        "Designed sub-millisecond portfolio calculation engine processing $4.2B in client assets using TypeScript, WebSockets, and Redis.",
        "Engineered accessible component system adopted across 8 distinct fintech applications, slashing design QA iterations by 60%.",
        "Spearheaded SOC2 compliance audit readiness across 24 cloud services with zero major non-conformances.",
      ],
    },
    {
      id: "exp-3",
      role: "Software Engineer",
      company: "Vanguard Labs",
      location: "Austin, TX",
      startDate: "2017-01",
      endDate: "2019-05",
      current: false,
      bullets: [
        "Built responsive real-time dashboards utilizing React, GraphQL, and PostgreSQL serving 450k monthly active users.",
        "Optimized frontend bundle size by 54% through aggressive code-splitting and dynamic imports, boosting Core Web Vitals to 98/100.",
      ],
    },
  ],
  education: [
    {
      id: "edu-1",
      degree: "B.S. in Computer Science & Applied Mathematics",
      institution: "University of California, Berkeley",
      location: "Berkeley, CA",
      startDate: "2013-09",
      endDate: "2017-05",
      gpa: "3.88 / 4.0",
      honors: "Summa Cum Laude, Dean's Honors List (All Semesters)",
    },
  ],
  skills: [
    { id: "sk-1", name: "TypeScript / JavaScript", category: "Languages", level: 5 },
    { id: "sk-2", name: "React / Next.js", category: "Frontend", level: 5 },
    { id: "sk-3", name: "Node.js & Go", category: "Backend", level: 5 },
    { id: "sk-4", name: "PostgreSQL & Redis", category: "Databases", level: 4 },
    { id: "sk-5", name: "AWS & Kubernetes", category: "Cloud & DevOps", level: 4 },
    { id: "sk-6", name: "GraphQL & RESTful APIs", category: "Architecture", level: 5 },
    { id: "sk-7", name: "Tailwind CSS & Design Systems", category: "Frontend", level: 5 },
    { id: "sk-8", name: "CI/CD & Docker", category: "Cloud & DevOps", level: 4 },
  ],
  projects: [
    {
      id: "proj-1",
      name: "StreamCast Open Protocol",
      description:
        "Open-source P2P audio streaming protocol with sub-50ms latency over WebRTC and UDP.",
      techStack: ["Rust", "TypeScript", "WebRTC", "WASM"],
      link: "https://streamcast.dev",
      github: "https://github.com/alexrivera/streamcast",
    },
    {
      id: "proj-2",
      name: "FastKV In-Memory Store",
      description:
        "High-concurrency key-value engine with automatic snapshotting and Raft consensus.",
      techStack: ["Go", "Raft", "gRPC", "Docker"],
      link: "https://github.com/alexrivera/fastkv",
      github: "https://github.com/alexrivera/fastkv",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "AWS Certified Solutions Architect - Professional",
      issuer: "Amazon Web Services",
      date: "2023",
      url: "https://aws.amazon.com/certification",
    },
    {
      id: "cert-2",
      name: "Certified Kubernetes Administrator (CKA)",
      issuer: "Linux Foundation / CNCF",
      date: "2022",
      url: "https://cncf.io",
    },
  ],
  customSections: [],
  sectionOrder: [
    "summary",
    "experience",
    "skills",
    "projects",
    "education",
    "certifications",
  ],
  themeConfig: {
    templateId: "modern-tech",
    fontFamily: "inter",
    fontSize: "base",
    accentColor: "#0284c7", // Sky blue
    spacing: "standard",
    showAvatar: true,
    showIcons: true,
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const emptyResumeData: ResumeData = {
  id: "",
  title: "Untitled Resume",
  personalInfo: {
    fullName: "",
    jobTitle: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    linkedin: "",
    github: "",
    avatarUrl: "",
  },
  summary: "",
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  customSections: [],
  sectionOrder: [
    "summary",
    "experience",
    "education",
    "skills",
    "projects",
    "certifications",
  ],
  themeConfig: {
    templateId: "modern-tech",
    fontFamily: "inter",
    fontSize: "base",
    accentColor: "#10b981", // Emerald
    spacing: "standard",
    showAvatar: false,
    showIcons: true,
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
